name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: get-tag
        run: |
          TITLE=$(gh issue view 5 --json "title" --jq ".title")
          VERSION=${TITLE#Next version: }
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft:
    needs: [get-tag]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: false
          tag: ${{ needs.get-tag.outputs.tag }}
          version: ${{ needs.get-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft_prerelease:
    needs: [get-tag]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          disable-autolabeler: false
          config-name: release-drafter-alpha.yml
          prerelease: true
          latest: false
          prerelease-identifier: "alpha"
          tag: ${{ needs.get-tag.outputs.tag }}
          version: ${{ needs.get-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "${{ toJson(steps.release-drafter.outputs) }}"
